version: '3.7'
services:
  mongo:
    container_name: openhim-mongo_${HOSTNAME:-localhost}
    image: mongo:${MONGO_VERSION:-3.4}
    hostname: mongo_${HOSTNAME:-localhost}
    restart: always
    ports:
      - "${MONGO_EXPOSED_PORT:-27017}:27017"
    networks:
      - frontend
    volumes:
      - ./data:/data/db
    
  core:
    container_name: openhim-core_${HOSTNAME:-localhost}
    image: jembi/openhim-core:${OPENHIM_CORE_VERSION:-7.0.2}
    hostname: openhim-core_${HOSTNAME:-localhost}
    restart: always
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "${OPENHIM_CORE_API_EXPOSED_PORT:-8080}:8080"
      - "${OPENHIM_CORE_HTTPS_EXPOSED_PORT:-5000}:5000"
      - "${OPENHIM_CORE_HTTP_EXPOSED_PORT:-5001}:5001"      
      - "${OPENHIM_CORE_POOLING_EXPOSED_PORT:-7788}:7788"
    networks:
      - frontend
    volumes:
      - ./conf/openhim-core/default.json:/app/config/default.json
      - /etc/letsencrypt/live/HOST_NAME/fullchain.pem:/app/resources/certs/fullchain.pem
      - /etc/letsencrypt/live/HOST_NAME/privkey.pem:/app/resources/certs/privkey.pem
    depends_on:
      - mongo
  
  console:
    container_name: openhim-console_${HOSTNAME:-localhost}
    image: jembi/openhim-console:${OPENHIM_CONSOLE_VERSION:-1.14.3}
    hostname: openhim-console_${HOSTNAME:-localhost}
    restart: always
    ports:
      - "${OPENHIM_CONSOLE_EXPOSED_PORT:-9000}:80"
    networks:
      - frontend
    volumes:
      - ./conf/openhim-console/default.json:/usr/share/nginx/html/config/default.json
      #- ./conf/openhim-console/bundle.js:/usr/share/nginx/html/bundle.js 
      # Keycloak
      #- ./conf/keycloak/index.html:/usr/share/nginx/html/index.html
      #- ./conf/keycloak/keycloak.js:/usr/share/nginx/html/keycloak.js
      #- ./conf/keycloak/keycloak.json:/usr/share/nginx/html/keycloak.json

volumes:
  mongo:
    driver: local
    
networks:
  frontend:
    name: network_${HOSTNAME:-localhost}
    driver: bridge
