version: '3.7'
services:
  mongo:
    container_name: openhim-mongo_${HOSTNAME:-localhost}
    image: mongo:${MONGO_VERSION:-3.4}
    hostname: mongo_${HOSTNAME:-localhost}
    restart: always
    ports:
      - "${MONGO_EXPOSED_PORT:-27017}:27017"
    networks:
      - frontend
    volumes:
      - ./data:/data/db
    
  core:
    container_name: openhim-core_${HOSTNAME:-localhost}
    image: jembi/openhim-core:${OPENHIM_CORE_VERSION:-7.0.2}
    hostname: openhim-core_${HOSTNAME:-localhost}
    restart: always
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "${OPENHIM_CORE_EXPOSED_PORT:-8080}:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    networks:
      - frontend
    volumes:
        - ./openhim.json:/app/config/default.json
        - /etc/letsencrypt/live/HOST_NAME/fullchain.pem:/app/resources/certs/fullchain.pem
        - /etc/letsencrypt/live/HOST_NAME/privkey.pem:/app/resources/certs/privkey.pem
    depends_on:
      - mongo
  
  console:
    container_name: openhim-console_${HOSTNAME:-localhost}
    image: jembi/openhim-console:${OPENHIM_CONSOLE_VERSION:-1.14.3}
    hostname: openhim-console_${HOSTNAME:-localhost}
    restart: always
    ports:
        - "${OPENHIM_CONSOLERE_EXPOSED_PORT:-9000}:80"
    networks:
      - frontend
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
      - ./bundle.js:/usr/share/nginx/html/bundle.js 
      # Keycloak
      #- ./index.html:/usr/share/nginx/html/index.html
      #- ./keycloak.js:/usr/share/nginx/html/keycloak.js
      #- ./keycloak.json:/usr/share/nginx/html/keycloak.json

volumes:
  mongo:
    driver: local
    
networks:
  frontend:
    name: network_${HOSTNAME:-localhost}
    driver: bridge
